[package]
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
name = "xi-term"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.0"
failure = "0.1.5"
futures = "0.1.27"
log = "0.4.6"
log4rs = "0.8.3"
termion = "1.5.3"
tokio = "0.1.21"
xdg = "2.2.0"
indexmap = "1.0.2"
xrl = "0.0.7"
serde = { version = "1.0.93", features = ["derive"] }
serde_json = "1.0.39"
json5 = "0.2.4"
shellexpand = "1.0"
sublime_fuzzy = "0.6.0"
